/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package VIEW;

import DAO.claseDetalleVentaDAO;
import DAO.clasePrendaDAO;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VistaDialogoDetalleVenta extends java.awt.Dialog {

    VistaInternaVentas vistaventas = new VistaInternaVentas();
    clasePrendaDAO prenda = new clasePrendaDAO();
    claseDetalleVentaDAO detalleventa = new claseDetalleVentaDAO();
    /**
     * Creates new form VistaDialogoDetalleVenta
     */
    public VistaDialogoDetalleVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Detalle de la venta");
        txtnumventa.setText(""+vistaventas.codigo);
       
        prenda.getPrendaCmb(cmbprenda);
        listarDetalleVenta(vistaventas.codigo);
       
        txtnumventa.setEnabled(false);
        txtnumventa.setDisabledTextColor(Color.BLACK);
        
        txtconsecutivo.setEnabled(false);
        txtconsecutivo.setDisabledTextColor(Color.BLACK);
        
        txtvalorunit.setEnabled(false);
        txtvalorunit.setDisabledTextColor(Color.BLACK);
        
        habilitarbotones();
    }

    
    public void traerPrecio(){
       int id = prenda.getid(cmbprenda.getSelectedItem().toString());
        double precio = prenda.getPrecio(id);
        txtvalorunit.setText(""+precio);
        
    }
    
    public void listarDetalleVenta(int numfac){
        detalleventa.listarporNVentas(tabladetalleventas, numfac);
    }
    
     public void limpiarTablaDetalleVentas() {
        DefaultTableModel modelo;
         String[] titulos = {"Consecutivo", "numero de venta", "Codigo prenda", "Cantidad","Valor unitario","Subtotal"};
        modelo = new DefaultTableModel(null, titulos);
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        tabladetalleventas.setModel(modelo);
    }
      public void limpiarcmb(){
       cmbprenda.removeAllItems();
      }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtconsecutivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbprenda = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnumventa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcant = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtvalorunit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalleventas = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Detalle de la factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 14), new java.awt.Color(204, 102, 0))); // NOI18N

        jToolBar1.setBackground(new java.awt.Color(255, 153, 102));
        jToolBar1.setRollover(true);

        btnagregar.setBackground(new java.awt.Color(255, 153, 102));
        btnagregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(0, 0, 0));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Añadir venta.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.setFocusable(false);
        btnagregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnagregar);

        btneditar.setBackground(new java.awt.Color(255, 153, 102));
        btneditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneditar.setForeground(new java.awt.Color(0, 0, 0));
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IconoEditar.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.setFocusable(false);
        btneditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneditar);

        btnguardar.setBackground(new java.awt.Color(255, 153, 102));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 0, 0));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IconoGuardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setFocusable(false);
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnguardar);

        btncancelar.setBackground(new java.awt.Color(255, 153, 102));
        btncancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(0, 0, 0));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IconoCancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setFocusable(false);
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btncancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncancelar);

        btneliminar.setBackground(new java.awt.Color(255, 153, 102));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(0, 0, 0));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconoeliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setToolTipText("");
        btneliminar.setFocusable(false);
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        btncerrar.setBackground(new java.awt.Color(255, 153, 102));
        btncerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(0, 0, 0));
        btncerrar.setText("Cerrar");
        btncerrar.setFocusable(false);
        btncerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncerrar);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Consecutivo:");

        txtconsecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsecutivoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Prenda:");

        cmbprenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbprendaMouseClicked(evt);
            }
        });
        cmbprenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprendaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Numero de venta:");

        txtnumventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumventaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cantidad:");

        txtcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantActionPerformed(evt);
            }
        });
        txtcant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Valor unitario");

        txtvalorunit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorunitActionPerformed(evt);
            }
        });
        txtvalorunit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalorunitKeyTyped(evt);
            }
        });

        tabladetalleventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladetalleventas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnumventa)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalorunit, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtconsecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtvalorunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtconsecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        if (txtnumventa.getText().equals("")|| txtcant.getText().equals("")||txtvalorunit.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "Error, por favor digite todos los campos");
        }else{
             int numventa = Integer.parseInt(txtnumventa.getText());
            //prenda
             int codprenda = prenda.getid(cmbprenda.getSelectedItem().toString());
            //fin prenda
            int cantidad = Integer.parseInt(txtcant.getText());
            double valoruni = Double.parseDouble(txtvalorunit.getText());
            
         String mensaje =  detalleventa.agregar(numventa, codprenda, cantidad, valoruni);
            JOptionPane.showMessageDialog(null, mensaje);

             cmbprenda.setSelectedItem(prenda.getNombre(codprenda));
            limpiarTablaDetalleVentas();
            listarDetalleVenta(numventa);
        }
        
       
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        int index = tabladetalleventas.getSelectedRow();
        int consecutivo = Integer.parseInt(String.valueOf(tabladetalleventas.getValueAt(index, 0)));
        int codprenda = Integer.parseInt(String.valueOf(tabladetalleventas.getValueAt(index, 2)));
        int  cantidad = Integer.parseInt(String.valueOf(tabladetalleventas.getValueAt(index, 3)));
        double  valunitario = Double.parseDouble(String.valueOf(tabladetalleventas.getValueAt(index, 4)));
       
        
      
        txtconsecutivo.setText(""+consecutivo);
        
        cmbprenda.setSelectedItem(prenda.getNombre(codprenda));
        txtcant.setText(""+cantidad);
        txtvalorunit.setText(""+valunitario);
        
        deshabilitarbotones();
       
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        int numventa = Integer.parseInt(txtnumventa.getText());
        //prenda
        int codprenda = prenda.getid(cmbprenda.getSelectedItem().toString());
        //fin prenda
        int cantidad = Integer.parseInt(txtcant.getText());
        double valoruni = Double.parseDouble(txtvalorunit.getText());
        int consecutivo = Integer.parseInt(txtconsecutivo.getText());
        
        String mensaje =detalleventa.editar(numventa, codprenda, cantidad, valoruni,consecutivo);
        
       JOptionPane.showMessageDialog(null, mensaje);
        habilitarbotones();
        limpiarTablaDetalleVentas();
        listarDetalleVenta(numventa);

        txtcant.setText("");
        txtvalorunit.setText("0.0");
      
       
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
  int op = JOptionPane.showConfirmDialog(null, "¿Desea cancelar la operación?", "Seleccione una opción", HEIGHT);
        if (JOptionPane.OK_OPTION == op) {
        habilitarbotones();
          txtcant.setText("");
        txtvalorunit.setText("0.0");
        txtconsecutivo.setText("");
        }      
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
             int index = tabladetalleventas.getSelectedRow();
        int consecutivo = Integer.parseInt(String.valueOf(tabladetalleventas.getValueAt(index,0)));
         int numventa = Integer.parseInt(txtnumventa.getText());
         int op = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el producto de la factura?", "Seleccione una opción", HEIGHT);
        if (JOptionPane.OK_OPTION == op) {
             String mensaje=detalleventa.eliminar(consecutivo);
             JOptionPane.showMessageDialog(null, mensaje);
             limpiarTablaDetalleVentas();
            listarDetalleVenta(numventa);
        }
     
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncerrarActionPerformed

    private void txtconsecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsecutivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconsecutivoActionPerformed

    private void txtnumventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumventaActionPerformed

    private void txtcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantActionPerformed

    private void txtvalorunitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorunitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorunitActionPerformed

    private void cmbprendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbprendaMouseClicked
      
    }//GEN-LAST:event_cmbprendaMouseClicked

    private void cmbprendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprendaActionPerformed
         traerPrecio();
    }//GEN-LAST:event_cmbprendaActionPerformed

    private void txtcantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantKeyTyped
         char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtcantKeyTyped

    private void txtvalorunitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorunitKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtvalorunitKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaDialogoDetalleVenta dialog = new VistaDialogoDetalleVenta(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
public void habilitarbotones(){
     btnagregar.setVisible(true);
    btneliminar.setVisible(true);
    btncerrar.setVisible(true);
    
    btnguardar.setVisible(false);
    btncancelar.setVisible(false);
}

public void deshabilitarbotones(){
    btnagregar.setVisible(false);
    btneliminar.setVisible(false);
    btncerrar.setVisible(false);
    
    btnguardar.setVisible(true);
    btncancelar.setVisible(true);
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cmbprenda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tabladetalleventas;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtconsecutivo;
    private javax.swing.JTextField txtnumventa;
    private javax.swing.JTextField txtvalorunit;
    // End of variables declaration//GEN-END:variables
}
