/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;


import DAO.claseMaterialDAO;
import DAO.clasePrendaDAO;
import DAO.claseTipoPrendaDAO;
import MODEL.claseImagenMySQL;
import java.awt.Desktop;

import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author Usuario
 */
public class VistaInternaPrendas extends javax.swing.JInternalFrame {

    clasePrendaDAO prenda = new clasePrendaDAO();
    claseMaterialDAO material = new claseMaterialDAO();
    claseTipoPrendaDAO tipoprenda = new claseTipoPrendaDAO();

    private static File archivo;
    private static InputStream imagen = null;

    /**
     * Creates new form VistaInternaClientes
     */
    public VistaInternaPrendas() {
        initComponents();
        this.setTitle("Prendas");
      
        prenda.listarPrendas(tablaprendas);
        btnguardar.setVisible(false);
        btncancelar.setVisible(false);
        material.getMaterialcmb(cmbmaterial);
        tipoprenda.getTipoPrendacmb(cmbtipoprenda);
    }

    public void limpiarcajas() {
        txidprenda.setText("");
        txtnomprenda.setText("");
        txtcolor.setText("");
        txtprecio.setText("");
        txtfecha.setText("");

        panelimgprenda.removeAll();
        panelimgprenda.repaint();

    }

    public void limpiartablaPrendas() {
        DefaultTableModel modelo;
        String[] titulos = {"ID", "Nombre", "Color", "Categoria", "Cod material", "Cod tipo prenda", "Precio", "Fecha creacion", "Fecha modificacion"};
        modelo = new DefaultTableModel(null, titulos);
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        tablaprendas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnagregar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnimportar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txidprenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnomprenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelimgprenda = new javax.swing.JPanel();
        btncargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaprendas = new javax.swing.JTable();
        cmbcategoria = new javax.swing.JComboBox<>();
        cmbmaterial = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbtipoprenda = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Gestionar prendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        jToolBar1.setBackground(new java.awt.Color(204, 204, 255));
        jToolBar1.setRollover(true);

        btnagregar.setBackground(new java.awt.Color(153, 153, 255));
        btnagregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(0, 0, 0));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconoañadirropa.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.setFocusable(false);
        btnagregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnagregar);

        btnbuscar.setBackground(new java.awt.Color(153, 153, 255));
        btnbuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconobuscar.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setToolTipText("");
        btnbuscar.setFocusable(false);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnbuscar);

        btneditar.setBackground(new java.awt.Color(153, 153, 255));
        btneditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneditar.setForeground(new java.awt.Color(0, 0, 0));
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IconoEditar.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.setFocusable(false);
        btneditar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneditar);

        btnimportar.setBackground(new java.awt.Color(153, 153, 255));
        btnimportar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnimportar.setForeground(new java.awt.Color(0, 0, 0));
        btnimportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IconoExcel.png"))); // NOI18N
        btnimportar.setText("Importar");
        btnimportar.setToolTipText("");
        btnimportar.setFocusable(false);
        btnimportar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnimportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnimportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimportarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnimportar);

        btnguardar.setBackground(new java.awt.Color(153, 153, 255));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(0, 0, 0));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IconoGuardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setFocusable(false);
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnguardar);

        btncancelar.setBackground(new java.awt.Color(153, 153, 255));
        btncancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(0, 0, 0));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/IconoCancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setFocusable(false);
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btncancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncancelar);

        btneliminar.setBackground(new java.awt.Color(153, 153, 255));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(0, 0, 0));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconoeliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setToolTipText("");
        btneliminar.setFocusable(false);
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btneliminar);

        btnactualizar.setBackground(new java.awt.Color(153, 153, 255));
        btnactualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnactualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconoactualizartabla.png"))); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.setToolTipText("");
        btnactualizar.setFocusable(false);
        btnactualizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnactualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnactualizar);

        btncerrar.setBackground(new java.awt.Color(153, 153, 255));
        btncerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(0, 0, 0));
        btncerrar.setText("Cerrar");
        btncerrar.setFocusable(false);
        btncerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btncerrar);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID prenda:");

        txidprenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txidprendaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre Prenda:");

        txtnomprenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomprendaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Color:");

        txtcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcolorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Categoria:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Material:");

        panelimgprenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout panelimgprendaLayout = new javax.swing.GroupLayout(panelimgprenda);
        panelimgprenda.setLayout(panelimgprendaLayout);
        panelimgprendaLayout.setHorizontalGroup(
            panelimgprendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelimgprendaLayout.setVerticalGroup(
            panelimgprendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        btncargar.setBackground(new java.awt.Color(0, 102, 102));
        btncargar.setForeground(new java.awt.Color(255, 255, 255));
        btncargar.setText("Cargar");
        btncargar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarActionPerformed(evt);
            }
        });

        tablaprendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaprendas);

        cmbcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "mujer", "unisex" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tipo prenda:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Precio:");

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha:");

        txtfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfechaMouseClicked(evt);
            }
        });
        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtfecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(cmbcategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbtipoprenda, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelimgprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncargar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txtcolor)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txidprenda, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(5, 5, 5))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txidprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnomprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbtipoprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(30, 30, 30)))
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelimgprenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btncargar))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        if (txtnomprenda.getText().equals("") || txtcolor.getText().equals("")
                || txtprecio.getText().equals("") || txtfecha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios, complete todos los campos");
        } else {

            String nombreprenda = txtnomprenda.getText();
            String color = txtcolor.getText();
            String categoria = cmbcategoria.getSelectedItem().toString();
            int codmaterial = material.getid(cmbmaterial.getSelectedItem().toString());
            int codtipoprenda = tipoprenda.getid(cmbtipoprenda.getSelectedItem().toString());
            Double precio = Double.parseDouble(txtprecio.getText());
            String fecha = txtfecha.getText();

            String mensaje = prenda.agregar(nombreprenda, color, categoria, codmaterial, codtipoprenda, precio, fecha, fecha, archivo);

            JOptionPane.showMessageDialog(null, mensaje);

            limpiarcajas();
            limpiartablaPrendas();
            prenda.listarPrendas(tablaprendas);
            archivo=null;
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre de la prenda");
       
            boolean validar = prenda.listarPrenda(tablaprendas, nombre);
            if (validar == false) {
                JOptionPane.showMessageDialog(null, "No se encontro el dato");
                limpiarcajas();
                limpiartablaPrendas();
                prenda.listarPrendas(tablaprendas);
            }
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        
        int index = tablaprendas.getSelectedRow();
        int id = Integer.parseInt(String.valueOf(tablaprendas.getValueAt(index, 0)));
        String nombre = String.valueOf(tablaprendas.getValueAt(index, 1));
        String color = String.valueOf(tablaprendas.getValueAt(index, 2));
        String categoria = String.valueOf(tablaprendas.getValueAt(index, 3));
        int codmaterial = Integer.parseInt(String.valueOf(tablaprendas.getValueAt(index, 4)));
        int codtipoprenda = Integer.parseInt(String.valueOf(tablaprendas.getValueAt(index, 5)));
        double precio = Double.parseDouble(String.valueOf(tablaprendas.getValueAt(index, 6)));
       

        limpiarcajas();
        
        txidprenda.setText(""+id);
        txtnomprenda.setText(nombre);
        txtcolor.setText(color);
        cmbcategoria.setSelectedItem(categoria);
        txtprecio.setText(""+precio);
        deshabilitarBotones();
       
        
        cmbmaterial.setSelectedItem(material.getNombre(codmaterial));
        cmbtipoprenda.setSelectedItem(tipoprenda.getNombre(codtipoprenda));
        
         panelimgprenda.removeAll();
         imagen = prenda.getImageRute(id);
         archivo = null;
         BufferedImage buffimg = null;
          
        try {
            buffimg = ImageIO.read(imagen);
            claseImagenMySQL imagen = new claseImagenMySQL(panelimgprenda.getHeight(),panelimgprenda.getWidth(),buffimg);
                panelimgprenda.add(imagen);
                panelimgprenda.repaint();
        } catch (IOException ex) {
            Logger.getLogger(VistaInternaPrendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnimportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimportarActionPerformed
 //Crear el archivo
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Achivos de excel", "xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar archivo");
        chooser.setAcceptAllFileFilterUsed(false); //activa el cuadro de dialogo para guardar como
        if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            String ruta = chooser.getSelectedFile().toString().concat(".xls");
            try {
                //Crear el archivo de excel
                File archivoXLS = new File(ruta); //objeto tipo archivo
                if (archivoXLS.exists()) { //pregunta si el archivo existe
                    archivoXLS.delete();
                }
                archivoXLS.createNewFile();//crear el archivo
                Workbook libro = new HSSFWorkbook(); //creando el libro de excel
                FileOutputStream archivo = new FileOutputStream(archivoXLS);
                Sheet hoja = libro.createSheet("Datos"); //nombre de la hoja dentro del libro de excel
                hoja.setDisplayGridlines(false); //pongo en blanco las lineas de la hoja
                Row filTitulo = hoja.createRow(0);
                Cell celTitulo = filTitulo.createCell(0);
                celTitulo.setCellValue("LISTADO DE PRENDAS");
                int filaInicio = 1;
                for (int f = 0; f < tablaprendas.getRowCount(); f++) {
                    Row fila = hoja.createRow(filaInicio);//creo la fila
                    filaInicio++;
                    for (int c = 0; c < tablaprendas.getColumnCount(); c++) {
                        Cell celda = fila.createCell(c); //creo la celda
                        if (f == 0) {
                            celda.setCellValue(tablaprendas.getColumnName(c));
                        }
                    }
                }
                filaInicio = 2; //fila del archivo de excel
                for (int f = 0; f < tablaprendas.getRowCount(); f++) {
                    Row fila = hoja.createRow(filaInicio);
                    filaInicio++;
                    for (int c = 0; c < tablaprendas.getColumnCount(); c++) {
                        Cell celda = fila.createCell(c);
                        if (tablaprendas.getValueAt(f, c) instanceof Integer) {
                            celda.setCellValue(Integer.parseInt(tablaprendas.getValueAt(f, c).toString()));
                        } else {
                            celda.setCellValue(String.valueOf(tablaprendas.getValueAt(f, c)));
                        }
                    }
                }
                libro.write(archivo);
                archivo.close();
                Desktop.getDesktop().open(archivoXLS);
            } catch (IOException | NumberFormatException e) {
            }
        }
    }//GEN-LAST:event_btnimportarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
if (txidprenda.getText().equals("") || txtnomprenda.getText().equals("") || txtcolor.getText().equals("")
                || txtprecio.getText().equals("") || txtfecha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios, complete todos los campos");
        } else {
            
            int idprenda = Integer.parseInt(txidprenda.getText());
            String nombreprenda = txtnomprenda.getText();
            String color = txtcolor.getText();
            String categoria = cmbcategoria.getSelectedItem().toString();
            int codmaterial = material.getid(cmbmaterial.getSelectedItem().toString());
            int codtipoprenda = tipoprenda.getid(cmbtipoprenda.getSelectedItem().toString());
            Double precio = Double.parseDouble(txtprecio.getText());
            String fecha = txtfecha.getText();
            if (!(archivo == null)) {
            
            prenda.editarfoto(idprenda,nombreprenda, color, categoria, codmaterial, codtipoprenda, precio, fecha, archivo);
            limpiarcajas();
            limpiartablaPrendas();
            prenda.listarPrendas(tablaprendas);
            habilitarBotones();
            archivo = null;
        }else{
            
            prenda.editar(idprenda,nombreprenda, color, categoria, codmaterial, codtipoprenda, precio, fecha);
            limpiarcajas();
            limpiartablaPrendas();
            prenda.listarPrendas(tablaprendas);
            habilitarBotones();
            }       
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
     int op = JOptionPane.showConfirmDialog(rootPane, "¿Desea cancelar la operación?", "Seleccione una opción", HEIGHT);
        if (JOptionPane.OK_OPTION == op) {
        habilitarBotones();
         limpiarcajas();   
        }
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
    int index = tablaprendas.getSelectedRow();
        int id = Integer.parseInt(String.valueOf(tablaprendas.getValueAt(index,0)));
         int op = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar la prenda?", "Seleccione una opción", HEIGHT);
        if (JOptionPane.OK_OPTION == op) {
             String mensaje=prenda.eliminar(id);
             JOptionPane.showMessageDialog(null, mensaje);
             limpiartablaPrendas();
             prenda.listarPrendas(tablaprendas);
            }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        habilitarBotones();
        limpiarcajas();
        archivo = null;
        limpiartablaPrendas();
        prenda.listarPrendas(tablaprendas);
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncerrarActionPerformed

    private void txidprendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txidprendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txidprendaActionPerformed

    private void txtnomprendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomprendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomprendaActionPerformed

    private void txtcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcolorActionPerformed

    private void btncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.jpg", "jpg");
        fc.setFileFilter(filtro);

        int seleccion = fc.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();

        }
        BufferedImage buffimg = null;
        try {
            panelimgprenda.removeAll();
            buffimg = ImageIO.read(archivo);
            claseImagenMySQL imagen = new claseImagenMySQL(panelimgprenda.getHeight(), panelimgprenda.getWidth(), buffimg);
            panelimgprenda.add(imagen);
            panelimgprenda.repaint();

        } catch (IOException ex) {
            Logger.getLogger(VistaInternaPrendas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btncargarActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void txtfechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfechaMouseClicked
        if (txtfecha.getText().equals("")) {
            LocalDateTime fecha = LocalDateTime.now();
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/YYYY HH:mm:ss");
            txtfecha.setText(String.valueOf(fecha.format(formato)));
        }
    }//GEN-LAST:event_txtfechaMouseClicked

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtprecioKeyTyped

    public void deshabilitarBotones() {
        btnagregar.setVisible(false);
        btnbuscar.setVisible(false);
        btneditar.setVisible(false);
        btneliminar.setVisible(false);
        btncerrar.setVisible(false);
        btnimportar.setVisible(false);
        btnactualizar.setVisible(false);

        btnguardar.setVisible(true);
        btncancelar.setVisible(true);

    }

    public void habilitarBotones() {
        btnagregar.setVisible(true);
        btnbuscar.setVisible(true);
        btneditar.setVisible(true);
        btneliminar.setVisible(true);
        btncerrar.setVisible(true);
        btnimportar.setVisible(true);
        btnactualizar.setVisible(true);

        btnguardar.setVisible(false);
        btncancelar.setVisible(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnimportar;
    private javax.swing.JComboBox<String> cmbcategoria;
    private javax.swing.JComboBox<String> cmbmaterial;
    private javax.swing.JComboBox<String> cmbtipoprenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panelimgprenda;
    private javax.swing.JTable tablaprendas;
    private javax.swing.JTextField txidprenda;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtnomprenda;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
